//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UsbKey.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_SYSTEMTRAY                   101
#define IDD_PROPPAGE_KEYINFO            106
#define IDD_PROPPAGE_PWD                107
#define IDD_PROPPAGE_PROC               108
#define IDR_MAINFRAME                   128
#define IDI_ICONFILE                    129
#define IDI_ICON_KEY                    130
#define IDR_MENU_INFO                   131
#define IDI_ICON_ID                     131
#define IDI_ICON_DIRO                   133
#define IDB_BITMAP_OFF                  133
#define IDI_ICON_DIRC                   134
#define IDB_BITMAP_ON                   134
#define IDI_ICON_ROOT                   135
#define IDI_ICON_FREEDEVICE             136
#define IDI_ICON_FILE                   137
#define IDI_ICON_CERT                   138
#define IDI_ICON_DISK                   140
#define IDI_ICON_PWD                    141
#define IDI_ICONKEY                     142
#define IDI_ICONUNLOCK                  143
#define IDI_ICON_LOCK                   144
#define IDD_PROPPAGE_SO                 145
#define IDI_ICON_SO                     146
#define IDI_ICON_FORMAT                 150
#define IDI_ICON_VERIFY                 153
#define IDI_ICON_DEV                    154
#define IDI_ICON_ERROR                  157
#define IDI_ICON_OK                     158
#define IDI_ICON_WARING                 159
#define IDD_PROPPAGE_EXT                160
#define IDI_ICON_EXTERN                 161
#define IDD_PROPPAGE_CA                 162
#define IDI_ICON_CA                     163
#define IDD_PROPPAGE_SSLCLIENT          166
#define IDI_ICON_SERVER                 167
#define IDD_PROPPAGE_SSLSERVER          167
#define IDI_ICON_CLIENT                 168
#define IDD_PROPPAGE_EVP                168
#define IDD_PROPPAGE_RASERVER           169
#define IDR_ROOT_CERT                   174
#define IDR_ROOT_KEY                    175
#define IDR_CLIENT_KEY                  177
#define IDR_CLIENT_CERT                 178
#define IDR_SERVER_CERT                 179
#define IDR_SERVER_KEY                  180
#define IDI_ICON_EVP                    183
#define IDR_HTML                        184
#define IDI_ICON_RA                     186
#define IDC_BInitKey                    1000
#define IDC_EDIT_ID                     1000
#define IDC_EDIT_UPWD                   1001
#define IDC_EDIT_TYPE                   1001
#define IDC_EDIT_UPWD2                  1002
#define IDC_EDIT_SPACE                  1002
#define IDC_B_VERUSER                   1003
#define IDC_EDIT_READ                   1003
#define IDC_EDIT_UPWD3                  1004
#define IDC_EDIT_WRITE                  1004
#define IDC_EDIT_UPWD4                  1005
#define IDC_EDIT_CRYPT                  1005
#define IDC_B_MODPWD                    1006
#define IDC_EDIT_INPUTID                1006
#define IDC_TREE                        1007
#define IDC_EDIT_UPWD5                  1007
#define IDC_B_OK                        1008
#define IDC_B_UNLOCK                    1008
#define IDC_EDIT_UPWD6                  1008
#define IDC_EDIT                        1009
#define IDC_EDIT_PATH                   1009
#define IDC_LIST                        1009
#define IDC_B_MODPWD2                   1010
#define IDC_B_CANLE                     1010
#define IDC_EDIT_PASSWORD               1010
#define IDC_EDIT_PATH2                  1010
#define IDC_B_CRL                       1010
#define IDC_EDIT_PASSWORD2              1011
#define IDC_EDIT_RAND                   1012
#define IDC_B_MKROOT                    1012
#define IDC_B_GETRAND                   1013
#define IDC_EDIT_TESTMAX                1013
#define IDC_B_SELPATH                   1013
#define IDC_B_MKREQ                     1013
#define IDC_EDIT_LEN                    1014
#define IDC_EDIT_TESTCURRENT            1014
#define IDC_EDIT_PRIPWD                 1014
#define IDC_B_MKCERT                    1014
#define IDC_IPADDRESS_IP                1014
#define IDC_EDIT_SPWD                   1015
#define IDC_B_SELECTCERT                1015
#define IDC_B_ENCRIPT                   1015
#define IDC_B_SELPATH2                  1015
#define IDC_B_MKCERT2                   1015
#define IDC_B_WRITE                     1016
#define IDC_STATIC_STATE                1016
#define IDC_B_DECRIPT                   1016
#define IDC_STATIC_ON                   1016
#define IDC_B_VERSO                     1017
#define IDC_LIST_PROC                   1017
#define IDC_BSIGN                       1018
#define IDC_B_VERIFY                    1019
#define IDC_B_SEAL                      1020
#define IDC_B_OPEN                      1021
#define IDC_STATIC_OFF                  1022
#define IDC_B_ENC                       1023
#define IDC_B_DEC                       1024
#define IDC_RADIO_ENCRYPT_TYPE          1024
#define IDC_LIST_SO                     1025
#define IDC_B_SET                       1026
#define IDC_RADIO3                      1026
#define IDC_R_CHANGEP                   1026
#define IDC_B_FORMAT                    1027
#define IDC_STATIC_SOLOCK               1028
#define IDC_LIST_INFO                   1030
#define IDC_EDIT_CERT                   1032
#define IDC_PROGRESS                    1033
#define IDC_CHECK                       1034
#define IDC_EDIT_PRI                    1035
#define IDC_B_PRI                       1036
#define IDC_EDIT_OLD                    1037
#define IDC_EDIT_NEW                    1038
#define IDC_B_CHANGE                    1039
#define IDC_LIST_CERT                   1040
#define IDC_EDIT_VNEW                   1041
#define IDC_B_PARSE                     1042
#define IDC_B_KEY                       1042
#define IDC_B_PUB                       1043
#define IDC_B_PATH                      1044
#define IDC_R_PARSE                     1046
#define IDC_R_CREATE                    1047
#define IDC_B_PATH4                     1047
#define IDC_EDIT_P12                    1048
#define IDC_EDIT_KEY                    1049
#define IDC_BUTTON1                     1050
#define IDC_B_CHECK                     1050
#define IDC_BUTTON2                     1051
#define IDC_BUTTON3                     1052
#define IDC_LIST_CA                     1053
#define IDC_EDIT_C                      1054
#define IDC_EDIT_ST                     1055
#define IDC_EDIT_L                      1056
#define IDC_EDIT_O                      1057
#define IDC_EDIT_OU                     1058
#define IDC_EDIT_CN                     1059
#define IDC_EDIT_DAY                    1061
#define IDC_BPTOD                       1061
#define IDC_EDIT_SN                     1062
#define IDC_BDTOP                       1062
#define IDC_BSOUT                       1063
#define IDC_EDIT_E                      1064
#define IDC_BSIN                        1064
#define IDC_COMBO_L                     1065
#define IDC_BENC                        1065
#define IDC_BDEC                        1066
#define IDC_BSEAL                       1067
#define IDC_BOPENSEAL                   1068
#define IDC_BDIGEST                     1069
#define IDC_BRSACERT                    1070
#define IDC_CHECK_P12                   1071
#define IDC_BVSIGN                      1071
#define IDC_BRSAKEY                     1072
#define IDC_EDIT_INFILE                 1073
#define IDC_EDIT4                       1074
#define IDC_EDIT_OUTFILE                1075
#define IDC_RADIO                       1076
#define IDC_EDIT_DIGEST                 1076
#define IDC_RADIO2                      1077
#define IDC_EDITP                       1078
#define IDC_RADIO_SDBI                  1079
#define IDC_RADIO_IDEA                  1080
#define IDC_EDIT_PORT                   1082
#define IDC_B_CONNECT                   1083
#define IDC_LIST_CLIENT                 1084
#define IDC_B_DISCON                    1085
#define IDC_EDIT_SEND                   1086
#define IDC_B_SEND                      1087
#define IDC_LISTEN                      1087
#define IDC_LIST_SERVER                 1088
#define IDC_B_SENDF                     1088
#define IDC_B_SEND2                     1089
#define IDC_COM_IP                      1089
#define IDC_LIST_SERVER2                1089
#define IDC_COMBO_CRYPT                 1091
#define IDC_LIST_EVP                    1092
#define IDC_COMBO_DIGEST                1093
#define IDC_B_GETC                      1096
#define IDC_RADIO_ANYONE                10017
#define IDC_RADIO_PIN                   10018
#define IDC_RADIO_SOPIN                 10019
#define IDC_RADIO_NONE                  10020
#define IDC_RADIO_ANYONE2               10021
#define IDC_RADIO_PIN2                  10022
#define IDC_RADIO_SOPIN2                10023
#define IDC_RADIO_NONE2                 10024
#define ID_MENU_PUTFILE                 32771
#define ID_MENU_CREATEDIR               32772
#define ID_MENU_DELDIR                  32773
#define ID_MENU_DELFILE                 32774
#define ID_MENU_POPFILE                 32776
#define ID_MENU_KEYFILE                 32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
