//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Raclient.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW_INPUT              101
#define IDC_WZD3_TYPE                   101
#define IDD_DIALOGBAR                   103
#define IDS_STRING_PROGRESS             105
#define IDS_STRING_PROGRESS_QUERY       105
#define IDR_MAINFRAME                   128
#define IDR_RACLIETYPE                  129
#define IDD_FORMVIEW_AUDIT              131
#define IDD_FORMVIEW_MADE               133
#define IDD_DIALOG_LOGO                 137
#define IDD_FORMVIEW_REVOKE             138
#define IDI_ICON1                       144
#define IDB_BITMAP1                     150
#define IDI_ICON_ERROR                  157
#define IDI_ICON_OK                     158
#define IDI_ICON_WARING                 159
#define IDR_CLIENT_KEY                  177
#define IDR_CLIENT_CERT                 178
#define IDI_ICON2                       204
#define IDI_ICON3                       205
#define IDI_ICON4                       206
#define IDI_ICON5                       207
#define IDI_ICON6                       209
#define IDI_ICON7                       214
#define IDI_ICON8                       215
#define IDB_BITMAP2                     231
#define IDB_BITMAP3                     232
#define IDB_BITMAP4                     233
#define IDI_ICON_LOG                    237
#define IDI_ICON_LOGC                   238
#define IDI_ICON_IC                     239
#define IDI_ICON_I                      240
#define IDI_ICON_FAUDIT                 241
#define IDI_ICON_PAUDIT                 243
#define IDI_ICON_FMADE                  244
#define IDI_ICON_MADE                   245
#define IDI_ICON_CERT                   256
#define IDI_ICON_REVOKE                 257
#define IDI_ICON_FCRL                   258
#define IDI_ICON_MCRL                   259
#define IDI_ICON_SFIND                  262
#define IDI_ICON                        263
#define IDC_BUTTON_PASS                 1003
#define IDC_LIST_AUDITING               1008
#define IDC_BUTTON_AUDITING             1018
#define IDC_BUTTON5                     1019
#define IDC_CXY_Y                       1019
#define IDC_BUTTON_APPLY                1029
#define IDC_LIST_MADE                   1032
#define IDC_BUTTON_LINEANDMADE          1033
#define IDC_BUTTON_AUT_MADE             1034
#define IDC_BUTTON_CANCLE               1035
#define IDC_BUTTON_AUT_MADE2            1035
#define IDC_CXY_X                       1042
#define IDC_LIST_INFO                   1045
#define IDC_TAB_INFO                    1054
#define IDC_EDIT_IP                     1059
#define IDC_LIST_LOGO                   1060
#define IDC_EDIT_DAY                    1061
#define IDC_CHECK1                      1063
#define IDC_CHECK2                      1064
#define IDC_COMBO_L                     1065
#define IDC_CHECK3                      1066
#define IDC_CHECK4                      1067
#define IDC_CHECK5                      1068
#define IDC_CHECK6                      1069
#define IDC_CHECK7                      1070
#define IDC_CHECK8                      1071
#define IDC_CHECK9                      1072
#define IDC_CHECK10                     1073
#define IDC_CHECK11                     1074
#define IDC_CHECK12                     1075
#define IDC_CHECK13                     1076
#define IDC_CHECK14                     1077
#define IDC_CHECK15                     1078
#define IDC_CHECK16                     1079
#define IDC_CHECK17                     1080
#define IDC_CHECK18                     1081
#define IDC_EDIT_PORT                   1082
#define IDC_CHECK19                     1082
#define IDC_CHECK20                     1083
#define IDC_EDIT                        1090
#define IDC_COMBO                       1091
#define IDC_DATE_BEGIN                  1092
#define IDC_DATE_END                    1093
#define IDC_BUTTON_REVOKE               1097
#define IDC_LIST_REVOKE                 1098
#define IDC_B_CRL                       1100
#define IDC_STATIC_ICON                 1101
#define IDC_BUTTON_FIND                 1101
#define IDC_RADIO1                      1103
#define IDC_RADIO2                      1104
#define IDC_EDIT1                       10002
#define IDC_EDIT2                       10003
#define IDC_EDIT3                       10004
#define IDC_EDIT4                       10005
#define IDC_EDIT5                       10006
#define IDC_EDIT6                       10007
#define IDC_EDIT7                       10008
#define IDC_EDIT8                       10009
#define ID_MENUITEM32771                32771
#define ID_SYS_CONNECT                  32772
#define ID_SYS_DISCONNECT               32773
#define ID_INPUT_UNIT                   32775
#define ID_AUDITING_CERT                32777
#define ID_MADE_LINE                    32778
#define ID_MADE_MADE                    32779
#define ID_BUTTON32784                  32784
#define ID_BUTTON32786                  32786
#define ID_CERT_REVOKE                  32793
#define IDS_STRING_INFO                 61216
#define IDS_STRING6_FIND                61216
#define IDS_STRING_STATE                61217
#define IDS_STRING_COMMAND              61218
#define IDS_STRING_PROGRESS_COMMAND     61219
#define IDS_STRING_SELECT               61220

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
